### ISSUE TITLE
CRAN installation

### ISSUE THREAD

**Issue by eblchen** [zhiyhu/CIDER#6]
R version 4.1.2 (same as listed in vignettes)

> install.packages("CIDER")
Warning in install.packages :
  package ‘CIDER’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by zhiyhu** [comment]
Thank you for your interest in CIDER! Unfortunately, CIDER is currently unavailable on CRAN due to the recent upgrade of Seurat to version 5.
 
Nevertheless, it can still be downloaded from the CRAN Archive at https://cran.r-project.org/src/contrib/Archive/CIDER/, and installed using the command below in R:

```r
## replace the "path_to_pkg" with the real path
install.packages("path_to_pkg/CIDER_0.99.1.tar.gz", repos = NULL, type = "source")
``` 

If you encounter any further issues, please do not hesitate to reopen the issue or open another issue.
